### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by lcmtwn** [sommerper/filetype-color#16]
If Tree View is hidden and filetype-color is enabled error is thrown while it switches from Settings pane to file pane and vice versa. Stack trace is attached below.

Atom ver.: 0.182.0
filetype-color ver.: 0.1.4

Stack Trace:
TypeError: Cannot read property 'querySelectorAll' of null
  at FiletypeColorView.module.exports.FiletypeColorView.colorAll (/Users/cmlai/.atom/packages/filetype-color/lib/filetype-color-view.js:187:28)
  at /Users/cmlai/.atom/packages/filetype-color/lib/filetype-color-view.js:161:26

**Comment by bschaeffer** [comment]
This only happens when the tree view is hidden.
