### ISSUE TITLE
Failed to load the filetype-color package

### ISSUE THREAD

**Issue by yriveiro** [sommerper/filetype-color#26]
[Enter steps to reproduce below:]
1. open atom in terminal

**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.5
**Thrown From**: [filetype-color](https://github.com/sommerper/filetype-color) package, v0.1.4
### Stack Trace

Failed to load the filetype-color package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/yriveiro/.atom/packages/filetype-color/lib/filetype-color-view.js:18:28)
    at /Users/yriveiro/.atom/packages/filetype-color/lib/filetype-color-view.js:32:5
    at Object.<anonymous> (/Users/yriveiro/.atom/packages/filetype-color/lib/filetype-color-view.js:246:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/yriveiro/.atom/packages/filetype-color/lib/filetype-color.coffee:4:23)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "emmet",
      "autocomplete",
      "go-plus",
      "Zen",
      "autocomplete-plus-async",
      "minimap",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "symbols-tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ],
    "projectHome": "/Users/yriveiro/Development/github"
  },
  "filetype-color": {
    "enabled": "false"
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-cli-diff, v0.11.0
atom-html-preview, v0.1.6
atom-jshint, v1.5.0
atom-lint, v0.20.1
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
autocomplete-snippets, v1.2.0
color-picker, v1.6.0
docblockr, v0.6.3
editor-stats, v0.17.0
file-icons, v1.5.3
filetype-color, v0.1.4
git-history, v2.3.0
git-log, v0.3.0
git-plus, v4.4.11
git-tab-status, v1.6.0
language-jade, v0.3.0
linter, v0.12.0
linter-php, v0.0.12
omni-ruler, v0.3.1
phpunit, v1.0.9
phpunit-snippets, v0.1.0
pretty-json, v0.3.2
script, v2.18.0
seti-syntax, v0.3.3
space-tab, v0.1.0
travis-ci-status, v0.13.0
vim-mode, v0.43.0
wakatime, v4.0.1
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
This only occurs when using atom in 1.0 API Preview Mode. Therefore you have to start atom via `atom --one` command.

**Comment by jwhitcraft** [comment]
see #36
