### ISSUE TITLE
Uncaught NotFoundError: 

### ISSUE THREAD

**Issue by Twintails** [sommerper/filetype-color#9]
Uncaught NotFoundError: Failed to execute 'observe' on 'MutationObserver': The provided node was null.

Atom 0.172.0 
on toggle attempt

/Users/user/.atom/packages/filetype-color/lib/filetype-color-view.js:96

79 var target = document.querySelector('.panes .pane ul');
ul seems to have changed recently to tabs-bar???

looks like might need to remove 'li' from line 147 and 170 for the elements 
elements = paneView.querySelectorAll(".title");

-----Show Stack Trace------

Error: Failed to execute 'observe' on 'MutationObserver': The provided node was null.
  at Error (native)
  at FiletypeColorView.module.exports.FiletypeColorView.createPaneViewObserver (/Users/user/.atom/packages/filetype-color/lib/filetype-color-view.js:96:23)
  at FiletypeColorView.module.exports.FiletypeColorView.toggle (/Users/user/.atom/packages/filetype-color/lib/filetype-color-view.js:72:18)
  at atom-workspace.<anonymous> (/Users/user/.atom/packages/filetype-color/lib/filetype-color-view.js:43:30)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

**Comment by Twintails** [comment]
The change that caused this seems to have been reverted...
